CREATE DATABASE customer;
USE customer;
-- What is the total revenue generated by male female customers 
select gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

# Which customers used a discount but still spent more than the average amount
select customer_id,purchase_amount
from customer 
where discount_applied ='yes' and purchase_amount>=(select avg(purchase_amount) from customer);

# Which are the top 5 products with the highest average review rating?
SELECT item_purchased, avg(review_rating) as avg_rating FROM customer
GROUP BY item_purchased
ORDER BY 
    avg_rating DESC
LIMIT 5;

# Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

# Do subscriber spends more ? Compare Avg spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as ttal_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer 
group by subscription_status
order by total_revenue,avg_spend 
desc;

# Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

